/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__inlineLogicOrGlueOrTags_token1 = 1,
  aux_sym__inlineLogicOrGlueOrTags_token2 = 2,
  anon_sym_once = 3,
  anon_sym_BANG = 4,
  anon_sym_cycle = 5,
  anon_sym_AMP = 6,
  anon_sym_shuffle = 7,
  anon_sym_TILDE = 8,
  anon_sym_stopping = 9,
  anon_sym_DOLLAR = 10,
  anon_sym_click = 11,
  anon_sym_QMARK = 12,
  aux_sym_explicitSequence_token1 = 13,
  sym_sequenceDivider = 14,
  aux_sym_conditionExpression_token1 = 15,
  aux_sym_tag_token1 = 16,
  aux_sym_tag_token2 = 17,
  sym_textEsc = 18,
  sym_text = 19,
  sym_glue = 20,
  sym__inlineWS = 21,
  aux_sym__newline_token1 = 22,
  sym_source_file = 23,
  sym_TOP = 24,
  sym_mixedLine = 25,
  sym__mixedTextAndLogic = 26,
  aux_sym__contentText = 27,
  sym__inlineLogicOrGlueOrTags = 28,
  sym__inlineLogic = 29,
  sym__innerLogic = 30,
  sym_explicitSequence = 31,
  sym__sequenceObjects = 32,
  sym__inlineSequenceObjects = 33,
  sym_conditionExpression = 34,
  sym__innerExpressions = 35,
  sym_tag = 36,
  sym__newline = 37,
  aux_sym__multiNewlines = 38,
  aux_sym_TOP_repeat1 = 39,
  aux_sym_mixedLine_repeat1 = 40,
  aux_sym__mixedTextAndLogic_repeat1 = 41,
  aux_sym__mixedTextAndLogic_repeat2 = 42,
  aux_sym__inlineLogicOrGlueOrTags_repeat1 = 43,
  aux_sym_explicitSequence_repeat1 = 44,
  aux_sym__inlineSequenceObjects_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__inlineLogicOrGlueOrTags_token1] = "_inlineLogicOrGlueOrTags_token1",
  [aux_sym__inlineLogicOrGlueOrTags_token2] = "_inlineLogicOrGlueOrTags_token2",
  [anon_sym_once] = "once",
  [anon_sym_BANG] = "!",
  [anon_sym_cycle] = "cycle",
  [anon_sym_AMP] = "&",
  [anon_sym_shuffle] = "shuffle",
  [anon_sym_TILDE] = "~",
  [anon_sym_stopping] = "stopping",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_click] = "click",
  [anon_sym_QMARK] = "\?",
  [aux_sym_explicitSequence_token1] = "explicitSequence_token1",
  [sym_sequenceDivider] = "sequenceDivider",
  [aux_sym_conditionExpression_token1] = "conditionExpression_token1",
  [aux_sym_tag_token1] = "tag_token1",
  [aux_sym_tag_token2] = "tag_token2",
  [sym_textEsc] = "textEsc",
  [sym_text] = "text",
  [sym_glue] = "glue",
  [sym__inlineWS] = "_inlineWS",
  [aux_sym__newline_token1] = "_newline_token1",
  [sym_source_file] = "source_file",
  [sym_TOP] = "TOP",
  [sym_mixedLine] = "mixedLine",
  [sym__mixedTextAndLogic] = "_mixedTextAndLogic",
  [aux_sym__contentText] = "_contentText",
  [sym__inlineLogicOrGlueOrTags] = "_inlineLogicOrGlueOrTags",
  [sym__inlineLogic] = "_inlineLogic",
  [sym__innerLogic] = "_innerLogic",
  [sym_explicitSequence] = "explicitSequence",
  [sym__sequenceObjects] = "_sequenceObjects",
  [sym__inlineSequenceObjects] = "_inlineSequenceObjects",
  [sym_conditionExpression] = "conditionExpression",
  [sym__innerExpressions] = "_innerExpressions",
  [sym_tag] = "tag",
  [sym__newline] = "_newline",
  [aux_sym__multiNewlines] = "_multiNewlines",
  [aux_sym_TOP_repeat1] = "TOP_repeat1",
  [aux_sym_mixedLine_repeat1] = "mixedLine_repeat1",
  [aux_sym__mixedTextAndLogic_repeat1] = "_mixedTextAndLogic_repeat1",
  [aux_sym__mixedTextAndLogic_repeat2] = "_mixedTextAndLogic_repeat2",
  [aux_sym__inlineLogicOrGlueOrTags_repeat1] = "_inlineLogicOrGlueOrTags_repeat1",
  [aux_sym_explicitSequence_repeat1] = "explicitSequence_repeat1",
  [aux_sym__inlineSequenceObjects_repeat1] = "_inlineSequenceObjects_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__inlineLogicOrGlueOrTags_token1] = aux_sym__inlineLogicOrGlueOrTags_token1,
  [aux_sym__inlineLogicOrGlueOrTags_token2] = aux_sym__inlineLogicOrGlueOrTags_token2,
  [anon_sym_once] = anon_sym_once,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_cycle] = anon_sym_cycle,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_shuffle] = anon_sym_shuffle,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_stopping] = anon_sym_stopping,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_click] = anon_sym_click,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [aux_sym_explicitSequence_token1] = aux_sym_explicitSequence_token1,
  [sym_sequenceDivider] = sym_sequenceDivider,
  [aux_sym_conditionExpression_token1] = aux_sym_conditionExpression_token1,
  [aux_sym_tag_token1] = aux_sym_tag_token1,
  [aux_sym_tag_token2] = aux_sym_tag_token2,
  [sym_textEsc] = sym_textEsc,
  [sym_text] = sym_text,
  [sym_glue] = sym_glue,
  [sym__inlineWS] = sym__inlineWS,
  [aux_sym__newline_token1] = aux_sym__newline_token1,
  [sym_source_file] = sym_source_file,
  [sym_TOP] = sym_TOP,
  [sym_mixedLine] = sym_mixedLine,
  [sym__mixedTextAndLogic] = sym__mixedTextAndLogic,
  [aux_sym__contentText] = aux_sym__contentText,
  [sym__inlineLogicOrGlueOrTags] = sym__inlineLogicOrGlueOrTags,
  [sym__inlineLogic] = sym__inlineLogic,
  [sym__innerLogic] = sym__innerLogic,
  [sym_explicitSequence] = sym_explicitSequence,
  [sym__sequenceObjects] = sym__sequenceObjects,
  [sym__inlineSequenceObjects] = sym__inlineSequenceObjects,
  [sym_conditionExpression] = sym_conditionExpression,
  [sym__innerExpressions] = sym__innerExpressions,
  [sym_tag] = sym_tag,
  [sym__newline] = sym__newline,
  [aux_sym__multiNewlines] = aux_sym__multiNewlines,
  [aux_sym_TOP_repeat1] = aux_sym_TOP_repeat1,
  [aux_sym_mixedLine_repeat1] = aux_sym_mixedLine_repeat1,
  [aux_sym__mixedTextAndLogic_repeat1] = aux_sym__mixedTextAndLogic_repeat1,
  [aux_sym__mixedTextAndLogic_repeat2] = aux_sym__mixedTextAndLogic_repeat2,
  [aux_sym__inlineLogicOrGlueOrTags_repeat1] = aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [aux_sym_explicitSequence_repeat1] = aux_sym_explicitSequence_repeat1,
  [aux_sym__inlineSequenceObjects_repeat1] = aux_sym__inlineSequenceObjects_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__inlineLogicOrGlueOrTags_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inlineLogicOrGlueOrTags_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_once] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cycle] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shuffle] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stopping] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_click] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_explicitSequence_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_sequenceDivider] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_conditionExpression_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_textEsc] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_glue] = {
    .visible = true,
    .named = true,
  },
  [sym__inlineWS] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__newline_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_TOP] = {
    .visible = true,
    .named = true,
  },
  [sym_mixedLine] = {
    .visible = true,
    .named = true,
  },
  [sym__mixedTextAndLogic] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__contentText] = {
    .visible = false,
    .named = false,
  },
  [sym__inlineLogicOrGlueOrTags] = {
    .visible = false,
    .named = true,
  },
  [sym__inlineLogic] = {
    .visible = false,
    .named = true,
  },
  [sym__innerLogic] = {
    .visible = false,
    .named = true,
  },
  [sym_explicitSequence] = {
    .visible = true,
    .named = true,
  },
  [sym__sequenceObjects] = {
    .visible = false,
    .named = true,
  },
  [sym__inlineSequenceObjects] = {
    .visible = false,
    .named = true,
  },
  [sym_conditionExpression] = {
    .visible = true,
    .named = true,
  },
  [sym__innerExpressions] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__multiNewlines] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_TOP_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mixedLine_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__mixedTextAndLogic_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__mixedTextAndLogic_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inlineLogicOrGlueOrTags_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_explicitSequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inlineSequenceObjects_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_type = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 11,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 16,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 28,
  [31] = 27,
  [32] = 25,
  [33] = 33,
  [34] = 34,
  [35] = 26,
  [36] = 34,
  [37] = 33,
  [38] = 38,
  [39] = 25,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 41,
  [47] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '!', 34,
        '#', 47,
        '$', 40,
        '&', 36,
        ':', 43,
        '<', 4,
        '?', 42,
        '\\', 27,
        'c', 18,
        'o', 22,
        's', 14,
        '{', 31,
        '|', 44,
        '}', 32,
        '~', 38,
        '\t', 45,
        ' ', 45,
        '\n', 55,
        '\r', 55,
      );
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(54);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 34,
        '$', 40,
        '&', 36,
        '?', 42,
        'c', 18,
        'o', 22,
        's', 14,
        '~', 38,
        '\t', 46,
        ' ', 46,
      );
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '#', 47,
        '<', 4,
        '\\', 27,
        '{', 31,
        '|', 44,
        '}', 32,
        '\t', 50,
        ' ', 50,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '>' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(53);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'g') ADVANCE(39);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(26);
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'k') ADVANCE(41);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'y') ADVANCE(5);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 27:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 28:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '!', 34,
        '$', 40,
        '&', 36,
        ':', 43,
        '?', 42,
        'c', 18,
        'o', 22,
        's', 14,
        '}', 32,
        '~', 38,
        '\t', 54,
        ' ', 54,
        '\n', 55,
        '\r', 55,
      );
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '#', 47,
        '<', 4,
        '\\', 27,
        '{', 31,
        '\t', 51,
        ' ', 51,
        '\n', 55,
        '\r', 55,
      );
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '>' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(52);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__inlineLogicOrGlueOrTags_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__inlineLogicOrGlueOrTags_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_once);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_cycle);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_shuffle);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_stopping);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_click);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_explicitSequence_token1);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_sequenceDivider);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_conditionExpression_token1);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '|') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_conditionExpression_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_tag_token1);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_tag_token2);
      if (lookahead == ' ' ||
          lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_textEsc);
      if (lookahead == '\\') ADVANCE(27);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '|') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '<' &&
          lookahead != '>' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '<' &&
          lookahead != '>' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '<' &&
          lookahead != '>' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_glue);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__inlineWS);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym__newline_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 29},
  [3] = {.lex_state = 29},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 29},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 29},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 29},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 29},
  [15] = {.lex_state = 28},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 29},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 29},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 29},
  [30] = {.lex_state = 29},
  [31] = {.lex_state = 29},
  [32] = {.lex_state = 29},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 29},
  [36] = {.lex_state = 29},
  [37] = {.lex_state = 29},
  [38] = {.lex_state = 28},
  [39] = {.lex_state = 28},
  [40] = {.lex_state = 28},
  [41] = {.lex_state = 28},
  [42] = {.lex_state = 28},
  [43] = {.lex_state = 28},
  [44] = {.lex_state = 28},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 28},
  [47] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__inlineLogicOrGlueOrTags_token1] = ACTIONS(1),
    [aux_sym__inlineLogicOrGlueOrTags_token2] = ACTIONS(1),
    [anon_sym_once] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_cycle] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_shuffle] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_stopping] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_click] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [aux_sym_explicitSequence_token1] = ACTIONS(1),
    [sym_sequenceDivider] = ACTIONS(1),
    [aux_sym_conditionExpression_token1] = ACTIONS(1),
    [aux_sym_tag_token1] = ACTIONS(1),
    [sym_textEsc] = ACTIONS(1),
    [sym_glue] = ACTIONS(1),
    [sym__inlineWS] = ACTIONS(3),
    [aux_sym__newline_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(42),
    [sym_TOP] = STATE(43),
    [sym_mixedLine] = STATE(3),
    [sym__mixedTextAndLogic] = STATE(6),
    [aux_sym__contentText] = STATE(6),
    [sym__inlineLogicOrGlueOrTags] = STATE(6),
    [sym_tag] = STATE(6),
    [sym__newline] = STATE(21),
    [aux_sym__multiNewlines] = STATE(21),
    [aux_sym_TOP_repeat1] = STATE(3),
    [aux_sym_mixedLine_repeat1] = STATE(6),
    [aux_sym__mixedTextAndLogic_repeat1] = STATE(12),
    [aux_sym__mixedTextAndLogic_repeat2] = STATE(6),
    [aux_sym__inlineLogicOrGlueOrTags_repeat1] = STATE(6),
    [aux_sym__inlineLogicOrGlueOrTags_token1] = ACTIONS(5),
    [aux_sym_tag_token1] = ACTIONS(7),
    [sym_textEsc] = ACTIONS(9),
    [sym_text] = ACTIONS(11),
    [sym_glue] = ACTIONS(9),
    [sym__inlineWS] = ACTIONS(13),
    [aux_sym__newline_token1] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(22), 1,
      aux_sym_tag_token1,
    ACTIONS(28), 1,
      sym_text,
    ACTIONS(31), 1,
      sym__inlineWS,
    ACTIONS(34), 1,
      aux_sym__newline_token1,
    STATE(12), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(25), 2,
      sym_textEsc,
      sym_glue,
    STATE(2), 2,
      sym_mixedLine,
      aux_sym_TOP_repeat1,
    STATE(21), 2,
      sym__newline,
      aux_sym__multiNewlines,
    STATE(6), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym_mixedLine_repeat1,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [43] = 11,
    ACTIONS(5), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(7), 1,
      aux_sym_tag_token1,
    ACTIONS(11), 1,
      sym_text,
    ACTIONS(13), 1,
      sym__inlineWS,
    ACTIONS(15), 1,
      aux_sym__newline_token1,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(9), 2,
      sym_textEsc,
      sym_glue,
    STATE(2), 2,
      sym_mixedLine,
      aux_sym_TOP_repeat1,
    STATE(21), 2,
      sym__newline,
      aux_sym__multiNewlines,
    STATE(6), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym_mixedLine_repeat1,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [86] = 5,
    ACTIONS(3), 1,
      sym__inlineWS,
    ACTIONS(41), 1,
      aux_sym_conditionExpression_token1,
    STATE(15), 1,
      aux_sym_explicitSequence_repeat1,
    STATE(41), 5,
      sym__inlineLogic,
      sym__innerLogic,
      sym_explicitSequence,
      sym_conditionExpression,
      sym__innerExpressions,
    ACTIONS(39), 10,
      anon_sym_once,
      anon_sym_BANG,
      anon_sym_cycle,
      anon_sym_AMP,
      anon_sym_shuffle,
      anon_sym_TILDE,
      anon_sym_stopping,
      anon_sym_DOLLAR,
      anon_sym_click,
      anon_sym_QMARK,
  [115] = 5,
    ACTIONS(3), 1,
      sym__inlineWS,
    ACTIONS(41), 1,
      aux_sym_conditionExpression_token1,
    STATE(15), 1,
      aux_sym_explicitSequence_repeat1,
    STATE(46), 5,
      sym__inlineLogic,
      sym__innerLogic,
      sym_explicitSequence,
      sym_conditionExpression,
      sym__innerExpressions,
    ACTIONS(39), 10,
      anon_sym_once,
      anon_sym_BANG,
      anon_sym_cycle,
      anon_sym_AMP,
      anon_sym_shuffle,
      anon_sym_TILDE,
      anon_sym_stopping,
      anon_sym_DOLLAR,
      anon_sym_click,
      anon_sym_QMARK,
  [144] = 9,
    ACTIONS(5), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(7), 1,
      aux_sym_tag_token1,
    ACTIONS(13), 1,
      sym__inlineWS,
    ACTIONS(45), 1,
      sym_text,
    ACTIONS(47), 1,
      aux_sym__newline_token1,
    STATE(12), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(43), 2,
      sym_textEsc,
      sym_glue,
    STATE(20), 2,
      sym__newline,
      aux_sym__multiNewlines,
    STATE(10), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym_mixedLine_repeat1,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [180] = 8,
    ACTIONS(49), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(53), 1,
      aux_sym_tag_token1,
    ACTIONS(55), 1,
      sym_text,
    ACTIONS(57), 1,
      sym__inlineWS,
    STATE(17), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(44), 2,
      sym__sequenceObjects,
      sym__inlineSequenceObjects,
    ACTIONS(51), 3,
      sym_sequenceDivider,
      sym_textEsc,
      sym_glue,
    STATE(9), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
      aux_sym__inlineSequenceObjects_repeat1,
  [214] = 8,
    ACTIONS(59), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(62), 1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
    ACTIONS(67), 1,
      aux_sym_tag_token1,
    ACTIONS(70), 1,
      sym_text,
    ACTIONS(73), 1,
      sym__inlineWS,
    STATE(17), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(64), 3,
      sym_sequenceDivider,
      sym_textEsc,
      sym_glue,
    STATE(8), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
      aux_sym__inlineSequenceObjects_repeat1,
  [247] = 8,
    ACTIONS(49), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(53), 1,
      aux_sym_tag_token1,
    ACTIONS(57), 1,
      sym__inlineWS,
    ACTIONS(76), 1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
    ACTIONS(80), 1,
      sym_text,
    STATE(17), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(78), 3,
      sym_sequenceDivider,
      sym_textEsc,
      sym_glue,
    STATE(8), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
      aux_sym__inlineSequenceObjects_repeat1,
  [280] = 8,
    ACTIONS(82), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(85), 1,
      aux_sym_tag_token1,
    ACTIONS(91), 1,
      sym_text,
    ACTIONS(94), 1,
      sym__inlineWS,
    ACTIONS(97), 1,
      aux_sym__newline_token1,
    STATE(18), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(88), 2,
      sym_textEsc,
      sym_glue,
    STATE(10), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym_mixedLine_repeat1,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [312] = 4,
    STATE(27), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(101), 2,
      sym_text,
      sym__inlineWS,
    STATE(16), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
    ACTIONS(99), 6,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
      sym_sequenceDivider,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
  [335] = 8,
    ACTIONS(5), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(7), 1,
      aux_sym_tag_token1,
    ACTIONS(105), 1,
      sym_text,
    ACTIONS(107), 1,
      sym__inlineWS,
    ACTIONS(109), 1,
      aux_sym__newline_token1,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(103), 2,
      sym_textEsc,
      sym_glue,
    STATE(14), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [365] = 4,
    ACTIONS(114), 1,
      aux_sym_explicitSequence_token1,
    ACTIONS(116), 1,
      sym__inlineWS,
    STATE(13), 1,
      aux_sym_explicitSequence_repeat1,
    ACTIONS(111), 10,
      anon_sym_once,
      anon_sym_BANG,
      anon_sym_cycle,
      anon_sym_AMP,
      anon_sym_shuffle,
      anon_sym_TILDE,
      anon_sym_stopping,
      anon_sym_DOLLAR,
      anon_sym_click,
      anon_sym_QMARK,
  [387] = 4,
    STATE(31), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(101), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(99), 5,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
    STATE(19), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [409] = 4,
    ACTIONS(116), 1,
      sym__inlineWS,
    ACTIONS(120), 1,
      aux_sym_explicitSequence_token1,
    STATE(13), 1,
      aux_sym_explicitSequence_repeat1,
    ACTIONS(118), 10,
      anon_sym_once,
      anon_sym_BANG,
      anon_sym_cycle,
      anon_sym_AMP,
      anon_sym_shuffle,
      anon_sym_TILDE,
      anon_sym_stopping,
      anon_sym_DOLLAR,
      anon_sym_click,
      anon_sym_QMARK,
  [431] = 7,
    ACTIONS(122), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(127), 1,
      aux_sym_tag_token1,
    ACTIONS(133), 1,
      sym_text,
    ACTIONS(136), 1,
      sym__inlineWS,
    ACTIONS(125), 2,
      aux_sym__inlineLogicOrGlueOrTags_token2,
      sym_sequenceDivider,
    ACTIONS(130), 2,
      sym_textEsc,
      sym_glue,
    STATE(16), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [459] = 7,
    ACTIONS(49), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(53), 1,
      aux_sym_tag_token1,
    ACTIONS(107), 1,
      sym__inlineWS,
    ACTIONS(140), 1,
      sym_text,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(138), 2,
      sym_textEsc,
      sym_glue,
    STATE(11), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [486] = 7,
    ACTIONS(5), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(7), 1,
      aux_sym_tag_token1,
    ACTIONS(105), 1,
      sym_text,
    ACTIONS(107), 1,
      sym__inlineWS,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(103), 2,
      sym_textEsc,
      sym_glue,
    STATE(14), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [513] = 7,
    ACTIONS(125), 1,
      aux_sym__newline_token1,
    ACTIONS(136), 1,
      sym__inlineWS,
    ACTIONS(142), 1,
      aux_sym__inlineLogicOrGlueOrTags_token1,
    ACTIONS(145), 1,
      aux_sym_tag_token1,
    ACTIONS(151), 1,
      sym_text,
    ACTIONS(148), 2,
      sym_textEsc,
      sym_glue,
    STATE(19), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [540] = 4,
    STATE(38), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(156), 2,
      sym_text,
      sym__inlineWS,
    STATE(22), 2,
      sym__newline,
      aux_sym__multiNewlines,
    ACTIONS(154), 6,
      ts_builtin_sym_end,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
  [560] = 4,
    STATE(38), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(160), 2,
      sym_text,
      sym__inlineWS,
    STATE(22), 2,
      sym__newline,
      aux_sym__multiNewlines,
    ACTIONS(158), 6,
      ts_builtin_sym_end,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
  [580] = 6,
    ACTIONS(164), 1,
      sym_text,
    ACTIONS(166), 1,
      sym__inlineWS,
    ACTIONS(169), 1,
      aux_sym__newline_token1,
    STATE(38), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(22), 2,
      sym__newline,
      aux_sym__multiNewlines,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
  [604] = 4,
    ACTIONS(174), 1,
      aux_sym_tag_token1,
    ACTIONS(177), 2,
      sym_text,
      sym__inlineWS,
    STATE(23), 2,
      sym_tag,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
    ACTIONS(172), 5,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
      sym_sequenceDivider,
      sym_textEsc,
      sym_glue,
  [623] = 4,
    ACTIONS(179), 1,
      aux_sym_tag_token1,
    ACTIONS(177), 2,
      sym_text,
      sym__inlineWS,
    STATE(24), 2,
      sym_tag,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
    ACTIONS(172), 4,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
  [641] = 4,
    ACTIONS(184), 1,
      sym_text,
    ACTIONS(186), 1,
      sym__inlineWS,
    STATE(25), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(182), 6,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
      sym_sequenceDivider,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
  [659] = 5,
    ACTIONS(191), 1,
      sym_textEsc,
    ACTIONS(194), 1,
      sym_text,
    ACTIONS(197), 1,
      sym__inlineWS,
    STATE(26), 1,
      aux_sym__contentText,
    ACTIONS(189), 5,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
      sym_sequenceDivider,
      aux_sym_tag_token1,
      sym_glue,
  [679] = 3,
    STATE(25), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(201), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(199), 6,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
      sym_sequenceDivider,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
  [695] = 3,
    STATE(25), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(101), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(99), 6,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
      sym_sequenceDivider,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
  [711] = 2,
    ACTIONS(205), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(203), 6,
      ts_builtin_sym_end,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
  [724] = 3,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(101), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(99), 5,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
  [739] = 3,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(201), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(199), 5,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
  [754] = 4,
    ACTIONS(184), 1,
      sym_text,
    ACTIONS(207), 1,
      sym__inlineWS,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(182), 5,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
  [771] = 2,
    ACTIONS(212), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(210), 6,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
      sym_sequenceDivider,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
  [784] = 2,
    ACTIONS(216), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(214), 6,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
      sym_sequenceDivider,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
  [797] = 5,
    ACTIONS(197), 1,
      sym__inlineWS,
    ACTIONS(218), 1,
      sym_textEsc,
    ACTIONS(221), 1,
      sym_text,
    STATE(35), 1,
      aux_sym__contentText,
    ACTIONS(189), 4,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_glue,
      aux_sym__newline_token1,
  [816] = 2,
    ACTIONS(216), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(214), 5,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
  [828] = 2,
    ACTIONS(212), 2,
      sym_text,
      sym__inlineWS,
    ACTIONS(210), 5,
      aux_sym__inlineLogicOrGlueOrTags_token1,
      aux_sym_tag_token1,
      sym_textEsc,
      sym_glue,
      aux_sym__newline_token1,
  [840] = 3,
    ACTIONS(109), 1,
      aux_sym__newline_token1,
    ACTIONS(224), 1,
      sym__inlineWS,
    STATE(39), 1,
      aux_sym__mixedTextAndLogic_repeat1,
  [850] = 3,
    ACTIONS(182), 1,
      aux_sym__newline_token1,
    ACTIONS(226), 1,
      sym__inlineWS,
    STATE(39), 1,
      aux_sym__mixedTextAndLogic_repeat1,
  [860] = 2,
    ACTIONS(116), 1,
      sym__inlineWS,
    ACTIONS(229), 1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
  [867] = 2,
    ACTIONS(116), 1,
      sym__inlineWS,
    ACTIONS(232), 1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
  [874] = 2,
    ACTIONS(116), 1,
      sym__inlineWS,
    ACTIONS(234), 1,
      ts_builtin_sym_end,
  [881] = 2,
    ACTIONS(116), 1,
      sym__inlineWS,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
  [888] = 2,
    ACTIONS(116), 1,
      sym__inlineWS,
    ACTIONS(238), 1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
  [895] = 2,
    ACTIONS(3), 1,
      sym__inlineWS,
    ACTIONS(240), 1,
      aux_sym_tag_token2,
  [902] = 2,
    ACTIONS(116), 1,
      sym__inlineWS,
    ACTIONS(242), 1,
      aux_sym__inlineLogicOrGlueOrTags_token2,
  [909] = 2,
    ACTIONS(3), 1,
      sym__inlineWS,
    ACTIONS(244), 1,
      aux_sym_tag_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 115,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 214,
  [SMALL_STATE(9)] = 247,
  [SMALL_STATE(10)] = 280,
  [SMALL_STATE(11)] = 312,
  [SMALL_STATE(12)] = 335,
  [SMALL_STATE(13)] = 365,
  [SMALL_STATE(14)] = 387,
  [SMALL_STATE(15)] = 409,
  [SMALL_STATE(16)] = 431,
  [SMALL_STATE(17)] = 459,
  [SMALL_STATE(18)] = 486,
  [SMALL_STATE(19)] = 513,
  [SMALL_STATE(20)] = 540,
  [SMALL_STATE(21)] = 560,
  [SMALL_STATE(22)] = 580,
  [SMALL_STATE(23)] = 604,
  [SMALL_STATE(24)] = 623,
  [SMALL_STATE(25)] = 641,
  [SMALL_STATE(26)] = 659,
  [SMALL_STATE(27)] = 679,
  [SMALL_STATE(28)] = 695,
  [SMALL_STATE(29)] = 711,
  [SMALL_STATE(30)] = 724,
  [SMALL_STATE(31)] = 739,
  [SMALL_STATE(32)] = 754,
  [SMALL_STATE(33)] = 771,
  [SMALL_STATE(34)] = 784,
  [SMALL_STATE(35)] = 797,
  [SMALL_STATE(36)] = 816,
  [SMALL_STATE(37)] = 828,
  [SMALL_STATE(38)] = 840,
  [SMALL_STATE(39)] = 850,
  [SMALL_STATE(40)] = 860,
  [SMALL_STATE(41)] = 867,
  [SMALL_STATE(42)] = 874,
  [SMALL_STATE(43)] = 881,
  [SMALL_STATE(44)] = 888,
  [SMALL_STATE(45)] = 895,
  [SMALL_STATE(46)] = 902,
  [SMALL_STATE(47)] = 909,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_TOP, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inlineSequenceObjects, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mixedTextAndLogic, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__mixedTextAndLogic, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_explicitSequence_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_explicitSequence_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(5),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(45),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(16),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(16),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(4),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(47),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(19),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(19),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mixedLine, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mixedLine, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mixedLine, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mixedLine, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiNewlines, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__multiNewlines, 2, 0, 0),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__multiNewlines, 2, 0, 0), SHIFT_REPEAT(38),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiNewlines, 2, 0, 0), SHIFT_REPEAT(22),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inlineLogicOrGlueOrTags_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineLogicOrGlueOrTags_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inlineLogicOrGlueOrTags_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineLogicOrGlueOrTags_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat1, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__mixedTextAndLogic_repeat1, 2, 0, 0),
  [186] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__mixedTextAndLogic_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__contentText, 2, 0, 0),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__contentText, 2, 0, 0), SHIFT_REPEAT(26),
  [194] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contentText, 2, 0, 0), SHIFT_REPEAT(26),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__contentText, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mixedTextAndLogic, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__mixedTextAndLogic, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__newline, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__newline, 2, 0, 0),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__mixedTextAndLogic_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inlineLogicOrGlueOrTags, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__inlineLogicOrGlueOrTags, 3, 0, 0),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__contentText, 2, 0, 0), SHIFT_REPEAT(35),
  [221] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contentText, 2, 0, 0), SHIFT_REPEAT(35),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_conditionExpression, 1, 0, 0), REDUCE(sym__innerExpressions, 1, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [234] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicitSequence, 3, 0, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_engleri(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "engleri",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
