/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_once = 3,
  anon_sym_BANG = 4,
  anon_sym_cycle = 5,
  anon_sym_AMP = 6,
  anon_sym_shuffle = 7,
  anon_sym_TILDE = 8,
  anon_sym_stopping = 9,
  anon_sym_DOLLAR = 10,
  anon_sym_click = 11,
  anon_sym_QMARK = 12,
  anon_sym_COLON = 13,
  anon_sym_PIPE = 14,
  aux_sym_conditionExpression_token1 = 15,
  anon_sym_POUND = 16,
  aux_sym_tag_token1 = 17,
  sym_textEsc = 18,
  sym_text = 19,
  sym_glue = 20,
  sym__inlineWS = 21,
  aux_sym__newline_token1 = 22,
  sym_source_file = 23,
  sym_TOP = 24,
  sym_mixedLine = 25,
  sym__mixedTextAndLogic = 26,
  aux_sym__contentText = 27,
  sym__inlineLogicOrGlueOrTags = 28,
  sym__inlineLogic = 29,
  sym__innerLogic = 30,
  sym_explicitSequence = 31,
  sym__sequenceObjects = 32,
  sym__inlineSequenceObjects = 33,
  sym_conditionExpression = 34,
  sym__innerExpressions = 35,
  sym_tag = 36,
  sym__newline = 37,
  aux_sym__multiNewlines = 38,
  aux_sym_TOP_repeat1 = 39,
  aux_sym_mixedLine_repeat1 = 40,
  aux_sym__mixedTextAndLogic_repeat1 = 41,
  aux_sym__mixedTextAndLogic_repeat2 = 42,
  aux_sym__inlineLogicOrGlueOrTags_repeat1 = 43,
  aux_sym_explicitSequence_repeat1 = 44,
  aux_sym__inlineSequenceObjects_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_once] = "once",
  [anon_sym_BANG] = "!",
  [anon_sym_cycle] = "cycle",
  [anon_sym_AMP] = "&",
  [anon_sym_shuffle] = "shuffle",
  [anon_sym_TILDE] = "~",
  [anon_sym_stopping] = "stopping",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_click] = "click",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [aux_sym_conditionExpression_token1] = "conditionExpression_token1",
  [anon_sym_POUND] = "#",
  [aux_sym_tag_token1] = "tag_token1",
  [sym_textEsc] = "textEsc",
  [sym_text] = "text",
  [sym_glue] = "glue",
  [sym__inlineWS] = "_inlineWS",
  [aux_sym__newline_token1] = "_newline_token1",
  [sym_source_file] = "source_file",
  [sym_TOP] = "TOP",
  [sym_mixedLine] = "mixedLine",
  [sym__mixedTextAndLogic] = "_mixedTextAndLogic",
  [aux_sym__contentText] = "_contentText",
  [sym__inlineLogicOrGlueOrTags] = "_inlineLogicOrGlueOrTags",
  [sym__inlineLogic] = "_inlineLogic",
  [sym__innerLogic] = "_innerLogic",
  [sym_explicitSequence] = "explicitSequence",
  [sym__sequenceObjects] = "_sequenceObjects",
  [sym__inlineSequenceObjects] = "_inlineSequenceObjects",
  [sym_conditionExpression] = "conditionExpression",
  [sym__innerExpressions] = "_innerExpressions",
  [sym_tag] = "tag",
  [sym__newline] = "_newline",
  [aux_sym__multiNewlines] = "_multiNewlines",
  [aux_sym_TOP_repeat1] = "TOP_repeat1",
  [aux_sym_mixedLine_repeat1] = "mixedLine_repeat1",
  [aux_sym__mixedTextAndLogic_repeat1] = "_mixedTextAndLogic_repeat1",
  [aux_sym__mixedTextAndLogic_repeat2] = "_mixedTextAndLogic_repeat2",
  [aux_sym__inlineLogicOrGlueOrTags_repeat1] = "_inlineLogicOrGlueOrTags_repeat1",
  [aux_sym_explicitSequence_repeat1] = "explicitSequence_repeat1",
  [aux_sym__inlineSequenceObjects_repeat1] = "_inlineSequenceObjects_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_once] = anon_sym_once,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_cycle] = anon_sym_cycle,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_shuffle] = anon_sym_shuffle,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_stopping] = anon_sym_stopping,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_click] = anon_sym_click,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [aux_sym_conditionExpression_token1] = aux_sym_conditionExpression_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_tag_token1] = aux_sym_tag_token1,
  [sym_textEsc] = sym_textEsc,
  [sym_text] = sym_text,
  [sym_glue] = sym_glue,
  [sym__inlineWS] = sym__inlineWS,
  [aux_sym__newline_token1] = aux_sym__newline_token1,
  [sym_source_file] = sym_source_file,
  [sym_TOP] = sym_TOP,
  [sym_mixedLine] = sym_mixedLine,
  [sym__mixedTextAndLogic] = sym__mixedTextAndLogic,
  [aux_sym__contentText] = aux_sym__contentText,
  [sym__inlineLogicOrGlueOrTags] = sym__inlineLogicOrGlueOrTags,
  [sym__inlineLogic] = sym__inlineLogic,
  [sym__innerLogic] = sym__innerLogic,
  [sym_explicitSequence] = sym_explicitSequence,
  [sym__sequenceObjects] = sym__sequenceObjects,
  [sym__inlineSequenceObjects] = sym__inlineSequenceObjects,
  [sym_conditionExpression] = sym_conditionExpression,
  [sym__innerExpressions] = sym__innerExpressions,
  [sym_tag] = sym_tag,
  [sym__newline] = sym__newline,
  [aux_sym__multiNewlines] = aux_sym__multiNewlines,
  [aux_sym_TOP_repeat1] = aux_sym_TOP_repeat1,
  [aux_sym_mixedLine_repeat1] = aux_sym_mixedLine_repeat1,
  [aux_sym__mixedTextAndLogic_repeat1] = aux_sym__mixedTextAndLogic_repeat1,
  [aux_sym__mixedTextAndLogic_repeat2] = aux_sym__mixedTextAndLogic_repeat2,
  [aux_sym__inlineLogicOrGlueOrTags_repeat1] = aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [aux_sym_explicitSequence_repeat1] = aux_sym_explicitSequence_repeat1,
  [aux_sym__inlineSequenceObjects_repeat1] = aux_sym__inlineSequenceObjects_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_once] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cycle] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shuffle] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stopping] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_click] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_conditionExpression_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_textEsc] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_glue] = {
    .visible = true,
    .named = true,
  },
  [sym__inlineWS] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__newline_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_TOP] = {
    .visible = true,
    .named = true,
  },
  [sym_mixedLine] = {
    .visible = true,
    .named = true,
  },
  [sym__mixedTextAndLogic] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__contentText] = {
    .visible = false,
    .named = false,
  },
  [sym__inlineLogicOrGlueOrTags] = {
    .visible = false,
    .named = true,
  },
  [sym__inlineLogic] = {
    .visible = false,
    .named = true,
  },
  [sym__innerLogic] = {
    .visible = false,
    .named = true,
  },
  [sym_explicitSequence] = {
    .visible = true,
    .named = true,
  },
  [sym__sequenceObjects] = {
    .visible = false,
    .named = true,
  },
  [sym__inlineSequenceObjects] = {
    .visible = false,
    .named = true,
  },
  [sym_conditionExpression] = {
    .visible = true,
    .named = true,
  },
  [sym__innerExpressions] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__multiNewlines] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_TOP_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mixedLine_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__mixedTextAndLogic_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__mixedTextAndLogic_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inlineLogicOrGlueOrTags_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_explicitSequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inlineSequenceObjects_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_type = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 10,
  [18] = 15,
  [19] = 14,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 22,
  [29] = 29,
  [30] = 30,
  [31] = 26,
  [32] = 24,
  [33] = 33,
  [34] = 27,
  [35] = 25,
  [36] = 30,
  [37] = 29,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 24,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 38,
  [47] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '\t', 49,
        ' ', 43,
        '!', 32,
        '#', 44,
        '$', 38,
        '&', 34,
        ':', 41,
        '<', 2,
        '?', 40,
        '\\', 25,
        'c', 16,
        'o', 20,
        's', 12,
        '{', 29,
        '|', 42,
        '}', 30,
        '~', 36,
        '\n', 50,
        '\r', 50,
      );
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(49);
      if (lookahead == ' ') ADVANCE(45);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(50);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(48);
      END_STATE();
    case 3:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(24);
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(5);
      END_STATE();
    case 15:
      if (lookahead == 'k') ADVANCE(39);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(14);
      if (lookahead == 'y') ADVANCE(3);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 25:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 26:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '!', 32,
        '$', 38,
        '&', 34,
        ':', 41,
        '?', 40,
        'c', 16,
        'o', 20,
        's', 12,
        '}', 30,
        '~', 36,
        '\t', 49,
        ' ', 49,
        '\n', 50,
        '\r', 50,
      );
      END_STATE();
    case 27:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '#', 44,
        '<', 2,
        '\\', 25,
        '{', 29,
        '|', 42,
        '}', 30,
        '\t', 47,
        ' ', 47,
        '\n', 50,
        '\r', 50,
      );
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '>' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(47);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_once);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_cycle);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_shuffle);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_stopping);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_click);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_conditionExpression_token1);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_tag_token1);
      if (lookahead == ' ' ||
          lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_textEsc);
      if (lookahead == '\\') ADVANCE(25);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '<' &&
          lookahead != '>' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_glue);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__inlineWS);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym__newline_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 27},
  [3] = {.lex_state = 27},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 27},
  [7] = {.lex_state = 27},
  [8] = {.lex_state = 27},
  [9] = {.lex_state = 27},
  [10] = {.lex_state = 27},
  [11] = {.lex_state = 27},
  [12] = {.lex_state = 26},
  [13] = {.lex_state = 26},
  [14] = {.lex_state = 27},
  [15] = {.lex_state = 27},
  [16] = {.lex_state = 27},
  [17] = {.lex_state = 27},
  [18] = {.lex_state = 27},
  [19] = {.lex_state = 27},
  [20] = {.lex_state = 27},
  [21] = {.lex_state = 27},
  [22] = {.lex_state = 27},
  [23] = {.lex_state = 27},
  [24] = {.lex_state = 27},
  [25] = {.lex_state = 27},
  [26] = {.lex_state = 27},
  [27] = {.lex_state = 27},
  [28] = {.lex_state = 27},
  [29] = {.lex_state = 27},
  [30] = {.lex_state = 27},
  [31] = {.lex_state = 27},
  [32] = {.lex_state = 27},
  [33] = {.lex_state = 27},
  [34] = {.lex_state = 27},
  [35] = {.lex_state = 27},
  [36] = {.lex_state = 27},
  [37] = {.lex_state = 27},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 26},
  [40] = {.lex_state = 26},
  [41] = {.lex_state = 26},
  [42] = {.lex_state = 26},
  [43] = {.lex_state = 26},
  [44] = {.lex_state = 26},
  [45] = {.lex_state = 26},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 26},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_once] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_cycle] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_shuffle] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_stopping] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_click] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [aux_sym_conditionExpression_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_textEsc] = ACTIONS(1),
    [sym_glue] = ACTIONS(1),
    [sym__inlineWS] = ACTIONS(3),
    [aux_sym__newline_token1] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [sym_TOP] = STATE(44),
    [sym_mixedLine] = STATE(2),
    [sym__mixedTextAndLogic] = STATE(7),
    [aux_sym__contentText] = STATE(7),
    [sym__inlineLogicOrGlueOrTags] = STATE(7),
    [sym_tag] = STATE(7),
    [sym__newline] = STATE(20),
    [aux_sym__multiNewlines] = STATE(20),
    [aux_sym_TOP_repeat1] = STATE(2),
    [aux_sym_mixedLine_repeat1] = STATE(7),
    [aux_sym__mixedTextAndLogic_repeat1] = STATE(16),
    [aux_sym__mixedTextAndLogic_repeat2] = STATE(7),
    [aux_sym__inlineLogicOrGlueOrTags_repeat1] = STATE(7),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
    [sym_textEsc] = ACTIONS(11),
    [sym_text] = ACTIONS(11),
    [sym_glue] = ACTIONS(11),
    [sym__inlineWS] = ACTIONS(13),
    [aux_sym__newline_token1] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      sym__inlineWS,
    ACTIONS(15), 1,
      aux_sym__newline_token1,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(3), 2,
      sym_mixedLine,
      aux_sym_TOP_repeat1,
    STATE(20), 2,
      sym__newline,
      aux_sym__multiNewlines,
    ACTIONS(11), 3,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(7), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym_mixedLine_repeat1,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [41] = 10,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(24), 1,
      anon_sym_POUND,
    ACTIONS(30), 1,
      sym__inlineWS,
    ACTIONS(33), 1,
      aux_sym__newline_token1,
    STATE(16), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(3), 2,
      sym_mixedLine,
      aux_sym_TOP_repeat1,
    STATE(20), 2,
      sym__newline,
      aux_sym__multiNewlines,
    ACTIONS(27), 3,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(7), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym_mixedLine_repeat1,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [82] = 6,
    ACTIONS(3), 1,
      sym__inlineWS,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(38), 1,
      aux_sym_conditionExpression_token1,
    STATE(13), 1,
      aux_sym_explicitSequence_repeat1,
    STATE(43), 5,
      sym__inlineLogic,
      sym__innerLogic,
      sym_explicitSequence,
      sym_conditionExpression,
      sym__innerExpressions,
    ACTIONS(36), 10,
      anon_sym_once,
      anon_sym_BANG,
      anon_sym_cycle,
      anon_sym_AMP,
      anon_sym_shuffle,
      anon_sym_TILDE,
      anon_sym_stopping,
      anon_sym_DOLLAR,
      anon_sym_click,
      anon_sym_QMARK,
  [114] = 6,
    ACTIONS(3), 1,
      sym__inlineWS,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(38), 1,
      aux_sym_conditionExpression_token1,
    STATE(13), 1,
      aux_sym_explicitSequence_repeat1,
    STATE(47), 5,
      sym__inlineLogic,
      sym__innerLogic,
      sym_explicitSequence,
      sym_conditionExpression,
      sym__innerExpressions,
    ACTIONS(36), 10,
      anon_sym_once,
      anon_sym_BANG,
      anon_sym_cycle,
      anon_sym_AMP,
      anon_sym_shuffle,
      anon_sym_TILDE,
      anon_sym_stopping,
      anon_sym_DOLLAR,
      anon_sym_click,
      anon_sym_QMARK,
  [146] = 8,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(44), 1,
      anon_sym_POUND,
    ACTIONS(46), 1,
      sym__inlineWS,
    STATE(15), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(41), 2,
      sym__sequenceObjects,
      sym__inlineSequenceObjects,
    ACTIONS(42), 4,
      anon_sym_PIPE,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(8), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
      aux_sym__inlineSequenceObjects_repeat1,
  [181] = 8,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      sym__inlineWS,
    ACTIONS(50), 1,
      aux_sym__newline_token1,
    STATE(16), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(21), 2,
      sym__newline,
      aux_sym__multiNewlines,
    ACTIONS(48), 3,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(11), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym_mixedLine_repeat1,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [215] = 8,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(44), 1,
      anon_sym_POUND,
    ACTIONS(46), 1,
      sym__inlineWS,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(54), 4,
      anon_sym_PIPE,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(9), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
      aux_sym__inlineSequenceObjects_repeat1,
  [249] = 8,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      anon_sym_POUND,
    ACTIONS(67), 1,
      sym__inlineWS,
    STATE(15), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(61), 4,
      anon_sym_PIPE,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(9), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
      aux_sym__inlineSequenceObjects_repeat1,
  [283] = 5,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(72), 1,
      sym__inlineWS,
    STATE(27), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(14), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
    ACTIONS(70), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
  [309] = 7,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_POUND,
    ACTIONS(83), 1,
      sym__inlineWS,
    ACTIONS(86), 1,
      aux_sym__newline_token1,
    STATE(18), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(80), 3,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(11), 7,
      sym__mixedTextAndLogic,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym_mixedLine_repeat1,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [339] = 4,
    ACTIONS(91), 1,
      anon_sym_COLON,
    STATE(12), 1,
      aux_sym_explicitSequence_repeat1,
    ACTIONS(5), 2,
      sym__inlineWS,
      aux_sym__newline_token1,
    ACTIONS(88), 10,
      anon_sym_once,
      anon_sym_BANG,
      anon_sym_cycle,
      anon_sym_AMP,
      anon_sym_shuffle,
      anon_sym_TILDE,
      anon_sym_stopping,
      anon_sym_DOLLAR,
      anon_sym_click,
      anon_sym_QMARK,
  [362] = 4,
    ACTIONS(95), 1,
      anon_sym_COLON,
    STATE(12), 1,
      aux_sym_explicitSequence_repeat1,
    ACTIONS(5), 2,
      sym__inlineWS,
      aux_sym__newline_token1,
    ACTIONS(93), 10,
      anon_sym_once,
      anon_sym_BANG,
      anon_sym_cycle,
      anon_sym_AMP,
      anon_sym_shuffle,
      anon_sym_TILDE,
      anon_sym_stopping,
      anon_sym_DOLLAR,
      anon_sym_click,
      anon_sym_QMARK,
  [385] = 7,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    ACTIONS(102), 1,
      anon_sym_POUND,
    ACTIONS(108), 1,
      sym__inlineWS,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
    ACTIONS(105), 3,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(14), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [414] = 7,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(44), 1,
      anon_sym_POUND,
    ACTIONS(112), 1,
      sym__inlineWS,
    STATE(24), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(110), 3,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(10), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [442] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(116), 1,
      sym__inlineWS,
    ACTIONS(118), 1,
      aux_sym__newline_token1,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(114), 3,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(17), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [470] = 4,
    ACTIONS(72), 1,
      sym__inlineWS,
    STATE(34), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(19), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
    ACTIONS(70), 6,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [492] = 7,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(112), 1,
      sym__inlineWS,
    STATE(24), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(114), 3,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(17), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [520] = 6,
    ACTIONS(100), 1,
      aux_sym__newline_token1,
    ACTIONS(108), 1,
      sym__inlineWS,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 1,
      anon_sym_POUND,
    ACTIONS(126), 3,
      sym_textEsc,
      sym_text,
      sym_glue,
    STATE(19), 5,
      aux_sym__contentText,
      sym__inlineLogicOrGlueOrTags,
      sym_tag,
      aux_sym__mixedTextAndLogic_repeat2,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
  [545] = 4,
    ACTIONS(131), 1,
      sym__inlineWS,
    STATE(40), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(23), 2,
      sym__newline,
      aux_sym__multiNewlines,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [565] = 4,
    ACTIONS(135), 1,
      sym__inlineWS,
    STATE(40), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(23), 2,
      sym__newline,
      aux_sym__multiNewlines,
    ACTIONS(133), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [585] = 5,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(139), 1,
      anon_sym_POUND,
    ACTIONS(142), 1,
      sym__inlineWS,
    STATE(22), 2,
      sym_tag,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
    ACTIONS(137), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_textEsc,
      sym_text,
      sym_glue,
  [607] = 5,
    ACTIONS(146), 1,
      sym__inlineWS,
    ACTIONS(149), 1,
      aux_sym__newline_token1,
    STATE(40), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    STATE(23), 2,
      sym__newline,
      aux_sym__multiNewlines,
    ACTIONS(144), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
  [629] = 4,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(154), 1,
      sym__inlineWS,
    STATE(24), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(152), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
  [648] = 5,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(162), 1,
      sym__inlineWS,
    STATE(25), 1,
      aux_sym__contentText,
    ACTIONS(159), 2,
      sym_textEsc,
      sym_text,
    ACTIONS(157), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_POUND,
      sym_glue,
  [669] = 4,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(72), 1,
      sym__inlineWS,
    STATE(24), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(70), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
  [688] = 4,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(166), 1,
      sym__inlineWS,
    STATE(24), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(164), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
  [707] = 4,
    ACTIONS(142), 1,
      sym__inlineWS,
    ACTIONS(168), 1,
      anon_sym_POUND,
    STATE(28), 2,
      sym_tag,
      aux_sym__inlineLogicOrGlueOrTags_repeat1,
    ACTIONS(137), 5,
      anon_sym_LBRACE,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [725] = 3,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(173), 1,
      sym__inlineWS,
    ACTIONS(171), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
  [741] = 3,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(177), 1,
      sym__inlineWS,
    ACTIONS(175), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
  [757] = 3,
    ACTIONS(72), 1,
      sym__inlineWS,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(70), 6,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [772] = 3,
    ACTIONS(179), 1,
      sym__inlineWS,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(152), 6,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [787] = 2,
    ACTIONS(184), 1,
      sym__inlineWS,
    ACTIONS(182), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [800] = 3,
    ACTIONS(166), 1,
      sym__inlineWS,
    STATE(32), 1,
      aux_sym__mixedTextAndLogic_repeat1,
    ACTIONS(164), 6,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [815] = 4,
    ACTIONS(162), 1,
      sym__inlineWS,
    STATE(35), 1,
      aux_sym__contentText,
    ACTIONS(186), 2,
      sym_textEsc,
      sym_text,
    ACTIONS(157), 4,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_glue,
      aux_sym__newline_token1,
  [832] = 2,
    ACTIONS(177), 1,
      sym__inlineWS,
    ACTIONS(175), 6,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [844] = 2,
    ACTIONS(173), 1,
      sym__inlineWS,
    ACTIONS(171), 6,
      anon_sym_LBRACE,
      anon_sym_POUND,
      sym_textEsc,
      sym_text,
      sym_glue,
      aux_sym__newline_token1,
  [856] = 3,
    ACTIONS(3), 1,
      sym__inlineWS,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(189), 1,
      aux_sym_tag_token1,
  [866] = 2,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym__inlineWS,
      aux_sym__newline_token1,
  [874] = 3,
    ACTIONS(118), 1,
      aux_sym__newline_token1,
    ACTIONS(193), 1,
      sym__inlineWS,
    STATE(42), 1,
      aux_sym__mixedTextAndLogic_repeat1,
  [884] = 2,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym__inlineWS,
      aux_sym__newline_token1,
  [892] = 3,
    ACTIONS(152), 1,
      aux_sym__newline_token1,
    ACTIONS(197), 1,
      sym__inlineWS,
    STATE(42), 1,
      aux_sym__mixedTextAndLogic_repeat1,
  [902] = 2,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym__inlineWS,
      aux_sym__newline_token1,
  [910] = 2,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym__inlineWS,
      aux_sym__newline_token1,
  [918] = 2,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym__inlineWS,
      aux_sym__newline_token1,
  [926] = 3,
    ACTIONS(3), 1,
      sym__inlineWS,
    ACTIONS(5), 1,
      aux_sym__newline_token1,
    ACTIONS(207), 1,
      aux_sym_tag_token1,
  [936] = 2,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym__inlineWS,
      aux_sym__newline_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 114,
  [SMALL_STATE(6)] = 146,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 215,
  [SMALL_STATE(9)] = 249,
  [SMALL_STATE(10)] = 283,
  [SMALL_STATE(11)] = 309,
  [SMALL_STATE(12)] = 339,
  [SMALL_STATE(13)] = 362,
  [SMALL_STATE(14)] = 385,
  [SMALL_STATE(15)] = 414,
  [SMALL_STATE(16)] = 442,
  [SMALL_STATE(17)] = 470,
  [SMALL_STATE(18)] = 492,
  [SMALL_STATE(19)] = 520,
  [SMALL_STATE(20)] = 545,
  [SMALL_STATE(21)] = 565,
  [SMALL_STATE(22)] = 585,
  [SMALL_STATE(23)] = 607,
  [SMALL_STATE(24)] = 629,
  [SMALL_STATE(25)] = 648,
  [SMALL_STATE(26)] = 669,
  [SMALL_STATE(27)] = 688,
  [SMALL_STATE(28)] = 707,
  [SMALL_STATE(29)] = 725,
  [SMALL_STATE(30)] = 741,
  [SMALL_STATE(31)] = 757,
  [SMALL_STATE(32)] = 772,
  [SMALL_STATE(33)] = 787,
  [SMALL_STATE(34)] = 800,
  [SMALL_STATE(35)] = 815,
  [SMALL_STATE(36)] = 832,
  [SMALL_STATE(37)] = 844,
  [SMALL_STATE(38)] = 856,
  [SMALL_STATE(39)] = 866,
  [SMALL_STATE(40)] = 874,
  [SMALL_STATE(41)] = 884,
  [SMALL_STATE(42)] = 892,
  [SMALL_STATE(43)] = 902,
  [SMALL_STATE(44)] = 910,
  [SMALL_STATE(45)] = 918,
  [SMALL_STATE(46)] = 926,
  [SMALL_STATE(47)] = 936,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_TOP, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_TOP_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inlineSequenceObjects, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inlineSequenceObjects_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mixedTextAndLogic, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__mixedTextAndLogic, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mixedLine_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_explicitSequence_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_explicitSequence_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(46),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(14),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(4),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(38),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat2, 2, 0, 0), SHIFT_REPEAT(19),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mixedLine, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mixedLine, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mixedLine, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mixedLine, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inlineLogicOrGlueOrTags_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineLogicOrGlueOrTags_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inlineLogicOrGlueOrTags_repeat1, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiNewlines, 2, 0, 0),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__multiNewlines, 2, 0, 0), SHIFT_REPEAT(40),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiNewlines, 2, 0, 0), SHIFT_REPEAT(23),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__mixedTextAndLogic_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__contentText, 2, 0, 0),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__contentText, 2, 0, 0), SHIFT_REPEAT(25),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__contentText, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mixedTextAndLogic, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__mixedTextAndLogic, 3, 0, 0),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inlineLogicOrGlueOrTags_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inlineLogicOrGlueOrTags, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__inlineLogicOrGlueOrTags, 3, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__mixedTextAndLogic_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__newline, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__newline, 2, 0, 0),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__contentText, 2, 0, 0), SHIFT_REPEAT(35),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [191] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicitSequence, 3, 0, 1),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__mixedTextAndLogic_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_conditionExpression, 1, 0, 0), REDUCE(sym__innerExpressions, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_engleri(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "engleri",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
